---
 title: "Подготовка воспроизводимых отчетов"
 author: "gtishckov@yandex.ru"
 format: 
   md:
     output-file: README.md
---

# Подготовка воспроизводимых отчетов

## Цель работы  
1. Развить практические навыки использования современного стека воспроизводимых исследований

2. Закрепить знания о современных сетевых протоколах прикладного уровня

## Исходные данные

1.  Программное обеспечение Windows 11

2.  Rstudio Desktop

3.  Интерпретатор языка R 4.4.1

## План

1. Подготовить рабочее окружение для работы с RStudio

2. Разработать отчет с использованием стека технологий Rmarkdown и Quarto

3. Оформить отчет в соответствии с шаблоном

## Шаги

1. Скачать и установить [R для Windows](https://cran.r-project.org/bin/windows/base/).

2. Скачать и установить [RStudio для Windows](https://posit.co/download/rstudio-desktop/).

3. Создать и сделать публичным репозиторий на github.com.

4. Создать файл README.md и написать отчет.

## Оценка результата

В результате выполнения работы отчет был подготовлен с использованием языка разметки Markdown.

## Вывод

Мы научились создавать и делать отчет в RStudio, а также загружать работы на GitHub.
